# This file configures the Hasura CLI, a local development (and deployment) tool.
# Other files adjacent to it configure the Hasura Server specified herein.

actions:
  handler_webhook_baseurl:
  kind:
endpoint:
metadata_directory:
migrations_directory:
seeds_directory:
version:
