# Project config file for SonarQube scans (run via GH actions)

sonar.projectKey=NASA-AMMOS_aerie-gateway
sonar.organization=nasa-ammos

# name and version displayed in the SonarCloud UI.
sonar.projectName="plandev-gateway"
sonar.projectVersion="4.2.1"

# Path of sources to analyze relative to the sonar-project.properties file
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
