name: ci

on:
  push:
    branches:
      - develop
    tags:
      - v*

env:
  REGISTRY: ghcr.io

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Install Dev Dependencies and Build
        run: |
          npm install
          npm run build
      - name: Install Production Dependencies
        run: |
          rm -rf node_modules
          npm install --only=production
      - name: Login to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Extract Metadata (tags and labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Delete Untagged Docker Images
        uses: camargo/delete-untagged-docker-images-action@v1
        with:
          github-token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
