name: lint

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  list:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Install Dev Dependencies and Build
        run: |
          npm install
          npm run build
      - name: Lint
        run: |
          npm run lint
      - name: Check formatting
        run: |
          npm run format:check
